# Generated by Django 3.2.3 on 2021-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_up',
            old_name='image_n',
            new_name='image_benner',
        ),
        migrations.AddField(
            model_name='image_up',
            name='image_logo',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
